name: Update Submodules

on:
 schedule:
  - cron: '* * * * *' # Runs every 1 minute
 workflow_dispatch: # Allows manual triggering

jobs:
 update:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
     with:
      fetch-depth: 0
      token: ${{ secrets.PAT }}
      submodules: recursive

   - name: Git config
     run: |
      git config user.name github-actions
      git config user.email github-actions@github.com

   - name: Update submodules
     run: |
      git submodule update --remote
      git diff --exit-code || {
        git add .
        git commit -m "Update submodules"
        git push
      }
