name: Update Submodules

on:
 repository_dispatch:
  types: [push]
 workflow_dispatch: # Keeps manual trigger option

jobs:
 update:
  runs-on: ubuntu-latest
  steps:
   - name: Verify webhook signature
     env:
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
     run: |
      echo "${{ toJson(github.event) }}" > payload.json
      signature=$(echo -n "${{ toJson(github.event) }}" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | sed 's/^.* //')
      if [ "${{ github.event.headers['X-Hub-Signature-256'] }}" != "sha256=$signature" ]; then
        echo "Invalid signature"
        exit 1
      fi

   - name: Checkout repository
     uses: actions/checkout@v3
     with:
      fetch-depth: 0
      token: ${{ secrets.PAT }}
      submodules: recursive

   - name: Git config
     run: |
      git config user.name github-actions
      git config user.email github-actions@github.com

   - name: Update submodules
     run: |
      git submodule update --remote
      git diff --exit-code || {
        git add .
        git commit -m "Update submodules"
        git push
      }
